### ISSUE TITLE
helm install failed

### ISSUE THREAD

**Issue by hexiang1219** [CloudDetail/apo#7]
I tried to install it and found an error when executing helm install.
![图片](https://github.com/user-attachments/assets/7a079ed8-97b9-4844-b6e0-ffe9b50ad32f)
Does the apo helm chart package have a github address?

**Comment by GNLMQNMB** [comment]
> I tried to install it and found an error when executing helm install. ![图片](https://private-user-images.githubusercontent.com/34543240/365499734-7a079ed8-97b9-4844-b6e0-ffe9b50ad32f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTIwMzAsIm5iZiI6MTcyNTg1MTczMCwicGF0aCI6Ii8zNDU0MzI0MC8zNjU0OTk3MzQtN2EwNzllZDgtOTdiOS00ODQ0LWI2ZTAtZmZlOWI1MGFkMzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAzMTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MWE2N2NlNjdiNTdmY2VkNzg2YWNlYjZmMWVlNjhiM2Y3ZmY5ZTFiNGExNzM2NDY0NjJlOTFjM2NiMDc0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9NJAWFtE0xGGJCgD4D4WyAi0qQ4yFrr6C08HPAv0Q90) Does the apo helm chart package have a github address?

Could you please let me know the version of your Kubernetes cluster? Based on your screenshot, it seems the installation failure is due to certain deprecated resources in a higher version. You may try using the cluster version provided in our documentation to deploy APO.
The Helm charts are temporarily not available in a public repository. You can try pulling them using the ’helm pull‘ command.

**Comment by hexiang1219** [comment]
My problem has been solved in the WeChat group, thank you

**Comment by GNLMQNMB** [comment]
Conclusion: Currently, APO cannot be deployed in a Kubernetes cluster with a version lower than 1.23. The reason is that some of the open-source components used have this version requirement. However, we are not utilizing the high-version features of these components, so if there is a greater demand in the future, it is possible to lower the version for compatibility.
